### ISSUE TITLE
选中页眉下面的文字，左边会闪出滚动条

### ISSUE THREAD

**Issue by rubyfruitchen** [kirklin/celeris-web#15]
### Describe the bug

![8378A885-9F40-40e3-B228-914F28EB04BE](https://github.com/kirklin/celeris-web/assets/57526904/3f369402-166d-460e-bd91-0a0cfc9d8142)
选中图片中的位置，页面左边会闪一下滚动条

### Reproduction

2502046039@qq.com

### System Info

```Shell
不应该闪出滚动条
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
![image](https://github.com/kirklin/celeris-web/assets/17453452/d7b83569-ab4b-45ca-8d67-11e49042d5cb)
