### ISSUE TITLE
问题：chat部分是不是还没有开发完成

### ISSUE THREAD

**Issue by Aaron-zon** [kirklin/celeris-web#20]
### Describe the bug

我在官网发现了一些问题，如
1、chat部分无法正常发送聊天信息
2、发送按钮和清空按钮显示不全
3、大部分功能按钮无法使用（编辑助手、点赞、踩、转发）
。。。
因此想确认一下这部分的功能是不是还没有开发完

### Reproduction

https://celeris-web.vercel.app/#/chat/index

### System Info

```Shell
https://celeris-web.vercel.app/#/chat/index
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
这部分目前只是UI。服务端代码已经快写完了。
