### ISSUE TITLE
Scrollbar may obscure content area 滚动条有可能遮挡内容区域

### ISSUE THREAD

**Issue by Aaron-zon** [kirklin/celeris-web#21]
### Describe the bug

如图所示,当页面内容过长时,会出现一个垂直滚动条。但滚动条目前的位置可能会遮挡右侧的图表和指标卡片,影响用户查看这些重要数据。

建议解决方案:

- 为数据卡片添加内边距,让出空间给滚动条显示。
- 尝试重新布局页面,在右侧预留出一定空间,专门用于显示滚动条。

![image](https://github.com/kirklin/celeris-web/assets/47178158/5118949e-50d7-4a9b-a191-2e0d145d0c88)

### Reproduction

https://celeris-web.vercel.app/#/dashboard/index

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
我觉得溢出不是问题，但是滚动条这个确实可以想办法让他展示在内容区域外

**Comment by kirklin** [comment]
进一步改进：等待寻找更好的解决方法，现在的方案会导致上下padding和左右的padding不一致。
![image](https://github.com/kirklin/celeris-web/assets/17453452/5f204ee8-bc4a-40c9-8fa4-c98a605bc6b7)
