### ISSUE TITLE
where are openai?

### ISSUE THREAD

**Issue by zhoubo416** [kirklin/celeris-web#5]
### Describe the bug

only in annotation 

### Reproduction

only in annotation 

### System Info

```Shell
only in annotation
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
The chatbot feature is currently under development. We're working hard on it and expect to release it soon. Thank you for your interest and patience!

**Comment by kirklin** [comment]
Link #10
